listen: 127.0.0.1:7799
feeds:
  not-a-tesla-app:
    title: Not a Tesla App
    link: https://www.notateslaapp.com/
    spec:
      item: article.index-news-mod
      values:
        title: h1 > a
        desc: div.news-description
        date: p.date
      title: '{{ .title.Text }} ({{ .date.Text }})'
      description: '{{ .desc.Html }}'
      link: title
      date: date
      date_format: January 2, 2006
